[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "portal"
version = "0.1.0"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
authors = [
    {name = "Ivan Higuera-Mendieta", email = "ihigueme@stanford.edu"},
]